### ISSUE TITLE
PISTON_REPO_URL value when selfhosted

### ISSUE THREAD

**Issue by amarjeetanandsingh** [engineer-man/piston#655]
Hi
I'm trying to host the piston in my own server which do not have connectivity to external world. I have installed required dependencies - 
* Docker
* Docker Compose
* Node JS 20

1. Downloaded the piston-master zip to my local laptop from github and copied it into the server.
2. Pulled the `ghcr.io/engineer-man/piston` image in my local laptop and copied its tar to the server and loaded it.
3. Started the `piston_api` container using the below docker-compose.yml file:-
```
version: '3.2'

services:
    api:
        image: ghcr.io/engineer-man/piston
        container_name: piston_api
        restart: always
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
        tmpfs:
            - /piston/jobs:exec,uid=1000,gid=1000,mode=711
            - /tmp:exec
```

Since the server didn't had the internet connectivity, I downloaded python package from https://github.com/engineer-man/piston/releases/download/pkgs/python-3.9.4.pkg.tar.gz in my local laptop, copied it into this server, and then extracted it into the `data/piston/packages/python/3.9.4` folder which is mapped to `piston/packages/python/3.9.4` inside the container.

`curl -H 'Content-Type: application/json' http://localhost:2000/api/v2/runtimes` returns an empty response `[]` and it do not consider the existing python folder inside the `/piston/packages` folder.

Now when I am trying to hit the `curl -X POST -H 'Content-Type: application/json' -d '{"language": "python", "version": "3.9.4"}' http://localhost:2000/api/v2/runtimes` endpoint of my piston container to install a package, it crashes saying `reason: getaddrinfo ENOTFOUND github.com`

It seems `PISTON_REPO_URL` is the value to tell piston_api container where to look for packages when it need to download. However, I don't want to install any new package. Just python is enough. 

I can't figure out how to make piston_api stop looking outside to git and work with the packages available in the `/piston/packages` folder?

/cc @HexF
