### ISSUE TITLE
Manual dockerfile build not working

### ISSUE THREAD

**Issue by Frohrer** [engineer-man/piston#690]
Building manually, using the dockerfile in ./api/ does not work. I get the following error:

```
/usr/local/bin/docker-entrypoint.sh: 8: exec: /piston_api/src/docker-entrypoint.sh: not found
```

Docker-compose.yml:

```yml
version: '3.2'

services:
    api:
        build: ./api/.
        container_name: piston_api
        restart: always
        privileged: true
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
        tmpfs:
            - /tmp:exec
```
